import mongoose,{Schema} from "mongoose";

const tagSchema = new Schema(
    {
        name:{
            type:String,
        },
        color:{
            type:String, //generated by ai
        }
    },{timestamp:true}
)

export const Tag = mongoose.model("Tag", tagSchema)