import mongoose,{Schema} from "mongoose";

const tagSchema = new Schema(
    {
        name:{
            type:String,
        },
        color:{
            type:String, //generated by ai
        },
        blogs:[{
            type:Schema.Types.ObjectId,
            ref:"Blog"
        }]
    },{timestamps:true}
)

export const Tag = mongoose.model("Tag", tagSchema)